-- Punjabi Welfare Trust — content migration (generated from SQLite)
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS collection_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  section VARCHAR(64) NOT NULL,
  data JSON NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_section (section)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS settings (
  `key` VARCHAR(64) PRIMARY KEY,
  data JSON NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS feedback (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  rating INT NULL,
  category VARCHAR(100),
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO admins (id, email, password_hash) VALUES (1, 'admin@punjabiwelfaretrust.org', '$2b$10$6OAC3t9k48htri2.lmBMw.8Rkfb6jWyF0cWyqe7l3/fZ5vkrfftg2') ON DUPLICATE KEY UPDATE email = email;
INSERT INTO collection_items (id, section, data, sort_order) VALUES (16, 'activities', '{"icon":"Stethoscope","label":"Medical Camp Assistance"}', 0) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (17, 'activities', '{"icon":"Share2","label":"Social Media Advocacy"}', 1) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (18, 'activities', '{"icon":"CalendarDays","label":"Event Management"}', 2) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (19, 'activities', '{"icon":"HandCoins","label":"Fundraising Support"}', 3) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (51, 'certificates', '{"image":"/uploads/certificate1.png","title":"Appreciation for Excellent Serving Towards Society","issuer":"Delhi Police — Station House Officer, Delhi Cantt","date":"June 2026","description":"Delhi Police commends Punjabi Welfare Trust for serving the community through educational support, awareness programs, free NDA coaching and library facilities, recognising its commitment to empowering youth and promoting social responsibility."}', 0) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (52, 'certificates', '{"image":"/uploads/certificate2.png","title":"Appreciation for Outstanding Social Service","issuer":"Indian Army — HQ Technical Group EME, Delhi Cantt","date":"June 2026","description":"Col Vikas Tomar, CIME (IM & NSC), acknowledges the commendable efforts of the Trust in serving society through educational and awareness initiatives that will go a long way in shaping the future of the young generation."}', 1) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (53, 'certificates', '{"image":"/uploads/certificate3.png","title":"Appreciation for Outstanding Contribution","issuer":"Military Engineer Service — Commander Works Engineer, Delhi Cantt","date":"May 2026","description":"Col Vidyut Mahato applauds the Trust''s free NDA coaching for aspiring candidates, free library facilities and free coaching classes for students of Class 6th to 12th, making quality education accessible to all sections of society."}', 2) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (54, 'certificates', '{"image":"/uploads/certificate4.png","title":"Appreciation Letter for G-20 Volunteering","issuer":"Delhi Police — Asstt. Commissioner of Police, South West District","date":"2023","description":"Recognises the exemplary volunteering services rendered by Trust members during the G-20 Summit, along with its splendid work in education — free tuition with study material and free books and coaching for Class X and XII students."}', 3) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (55, 'certificates', '{"image":"/uploads/certificate5.png","title":"Gratitude for G-20 Summit Support","issuer":"Border Security Force — 45 Bn BSF","date":"2023","description":"The BSF places on record its appreciation for the exceptional arrangements — fans, tentage, tables, chairs and water tanks — that kept the troops comfortable during the G-20 Summit 2023."}', 4) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (56, 'certificates', '{"image":"/uploads/certificate6.png","title":"Message of Appreciation","issuer":"Virender Singh Kadian — MLA, Govt of NCT of Delhi (Delhi Cantt)","date":"July 2023","description":"The Hon''ble MLA appreciates the Trust''s work for career empowerment of the young generation, environmental development, education and public health across Delhi/NCR, including its dedicated service during the COVID-19 pandemic."}', 5) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (57, 'certificates', '{"image":"/uploads/certificate7.png","title":"Blessings & Appreciation","issuer":"Gurdwara Prabandhak Committee (Regd.), Sadar Bazar, Delhi Cantt","date":"February 2023","description":"The Committee lauds the Trust for uplifting society by giving free education, books and uniforms to poor students, along with free eye check-ups and blood donation camps."}', 6) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (58, 'certificates', '{"image":"/uploads/certificate8.png","title":"Letter of Appreciation","issuer":"Resident Welfare Association, Village Old Nangal, Delhi Cantt","date":"January 2022","description":"The RWA thanks the Trust for distributing free books and stationery to poor children in slum areas and for its free education, eye-testing camps and blood donation drives."}', 7) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (20, 'committee', '{"name":"DEV RAJ AHUJA","role":"ADVISOR","photo":"/uploads/advisory-1.jpeg"}', 0) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (21, 'committee', '{"name":"PARAMJEET BINDRA","role":"ADVISOR","photo":"/uploads/advisory-2.jpeg"}', 1) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (22, 'committee', '{"name":"MADAN MOHAN MANGAL","role":"ADVISOR","photo":"/uploads/advisory-3.jpeg"}', 2) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (23, 'committee', '{"name":"NANAK SINGH","role":"ADVISOR","photo":"/uploads/advisory-4.jpeg"}', 3) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (24, 'committee', '{"name":"ARUN PANDEY","role":"ADVISOR","photo":"/uploads/advisory-5.jpeg"}', 4) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (25, 'committee', '{"name":"TARUN KUMAR BHAGRA","role":"ADVISOR","photo":"/uploads/advisory-6.jpeg"}', 5) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (26, 'committee', '{"name":"SARTEJPAL SINGH","role":"ADVISOR","photo":"/uploads/advisory-7.jpeg"}', 6) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (27, 'committee', '{"name":"RAJEEV KASHYAP","role":"ADVISOR","photo":"/uploads/advisory-8.jpeg"}', 7) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (28, 'committee', '{"name":"GURDEEP SINGH GILL","role":"ADVISOR","photo":"/uploads/advisory-9.jpeg"}', 8) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (29, 'committee', '{"name":"NAVINDER SINGH","role":"ADVISOR","photo":"/uploads/advisory-10.jpeg"}', 9) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (1, 'heroSlides', '{"image":"/uploads/work-1.jpeg","badge":"FREE EDUCATION INITIATIVE","title":"Educating the Future","description":"Providing free communication education and library services to aspiring students."}', 0) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (2, 'heroSlides', '{"image":"/uploads/work-2.jpeg","badge":"WINTER CLOTHING DRIVE","title":"Warmth for Every Family","description":"Distributing winter clothing to underprivileged families across Delhi and Punjab."}', 1) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (3, 'heroSlides', '{"image":"/uploads/work-3.jpeg","badge":"ECO FRIENDLY DIWALI","title":"Green Diwali Campaign","description":"Spreading awareness for a pollution-free, eco-friendly Diwali celebration."}', 2) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (8, 'posts', '{"image":"/uploads/work-1.jpeg","title":"Free Communication Education","description":"Providing free communication education to underprivileged children, empowering them with language and life skills for a brighter future."}', 0) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (9, 'posts', '{"image":"/uploads/work-2.jpeg","title":"Winter Clothing Distribution Drive","description":"Distributing warm clothes, blankets, and winter essentials to families in need during the harsh winter months across Delhi."}', 1) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (10, 'posts', '{"image":"/uploads/work-3.jpeg","title":"Eco Friendly Diwali Awareness Rally","description":"Organizing rallies and campaigns to promote eco-friendly Diwali celebrations, encouraging people to burst ego not crackers."}', 2) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (11, 'posts', '{"image":"/uploads/work-4.jpeg","title":"Candle Light Tribute & Peace March","description":"Holding candlelight vigils and peace marches to honor the sacrifices of our heroes and promote harmony in the community."}', 3) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (12, 'posts', '{"image":"/uploads/work-5.jpeg","title":"Annual Winter Relief","description":"Our annual winter relief program provides blankets, warm clothing, and food to homeless and underprivileged families across the region."}', 4) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (13, 'posts', '{"image":"/uploads/work-6.jpeg","title":"Langar Seva: Providing Nutritious Meals to Vulnerable Communities","description":"Serving hot, nutritious meals to hundreds of people every week through our community kitchen and langar seva program."}', 5) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (14, 'posts', '{"image":"/uploads/work-7.jpeg","title":"Covid-19 Relief Efforts","description":"Reaching out to the most vulnerable during the Covid-19 pandemic with essential supplies and support."}', 6) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (15, 'posts', '{"image":"/uploads/work-8.jpeg","title":"Library with books, stationery, and tutoring at no cost.","description":"Students can access educational resources and support without any cost and useful for all with providing teacher guidance."}', 7) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (4, 'stats', '{"icon":"MapPin","value":"50","label":"VILLAGES SERVED"}', 0) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (5, 'stats', '{"icon":"Users","value":"12000","label":"LIVES IMPACTED"}', 1) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (6, 'stats', '{"icon":"HandHeart","value":"150","label":"VOLUNTEERS"}', 2) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (7, 'stats', '{"icon":"School","value":"8","label":"SCHOOLS BUILT"}', 3) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (30, 'supporters', '{"name":"UMINDER SINGH","role":"PRESIDENT","photo":"/uploads/Supporter-16.jpeg"}', 0) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (31, 'supporters', '{"name":"BHARAT BHUSHAN SAHNI","role":"VICE-PRESIDENT","photo":"/uploads/supporter-18.jpeg"}', 1) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (32, 'supporters', '{"name":"H.S GROVER","role":"CHAIRMAN","photo":"/uploads/supporter-14.jpeg"}', 2) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (33, 'supporters', '{"name":"BHAGWANT SINGH","role":"VICE CHAIRMAN","photo":"/uploads/supporter-17.jpeg"}', 3) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (34, 'supporters', '{"name":"ATUL AGGARWAL","role":"GENERAL SECRETARY","photo":"/uploads/supporter-19.jpeg"}', 4) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (35, 'supporters', '{"name":"MANISH SHARMA","role":"SECRETARY-1","photo":"/uploads/supporter-11.jpeg"}', 5) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (36, 'supporters', '{"name":"AMIT KUMAR","role":"SECRETARY-2","photo":"/uploads/supporter-20.jpeg"}', 6) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (37, 'supporters', '{"name":"MANOO KAPOOR","role":"CASHIER","photo":"/uploads/supporter-12.jpeg"}', 7) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (38, 'supporters', '{"name":"MUNEET SHARMA","role":"MEDIA PRABHARI","photo":"/uploads/supporter-13.jpeg"}', 8) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (39, 'supporters', '{"name":"RAMESH DUTT BHAT","role":"TREASURER","photo":"/uploads/supporter-15.jpeg"}', 9) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (40, 'supporters', '{"name":"DILSAD","role":"TECH MEMBER","photo":"/uploads/dilsad.jpeg"}', 10) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (44, 'videos', '{"title":"Punjabi Welfare Trust - Our Mission","description":"Watch how our trust is making a difference in the lives of underprivileged communities.","thumbnail":"/uploads/yt-thumbnail3.jpeg","url":"https://www.youtube.com/@punjabiwelfaretrust99"}', 0) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (45, 'videos', '{"title":"Community Service Highlights","description":"Highlights from our feeding, education and healthcare drives across Delhi and Punjab.","thumbnail":"/uploads/yt-thumbnail2.jpeg","url":"https://www.youtube.com/@punjabiwelfaretrust99"}', 1) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (46, 'videos', '{"title":"Join the Movement","description":"See how volunteers and donors are coming together to build a better tomorrow.","thumbnail":"/uploads/yt-thumbnail.jpeg","url":"https://www.youtube.com/@punjabiwelfaretrust99"}', 2) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (41, 'volunteers', '{"name":"Madhur Sharma","role":"WEBSITE DEVELOPER","photo":"/uploads/volunteer-23.jpeg"}', 0) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (42, 'volunteers', '{"name":"Swejal Gupta","role":"WEBSITE DEVELOPER","photo":"/uploads/volSwejal.jpeg"}', 1) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO collection_items (id, section, data, sort_order) VALUES (43, 'volunteers', '{"name":"Prem Singh","role":"WEBSITE DEVELOPER","photo":"/uploads/volunteer-22.jpeg"}', 2) ON DUPLICATE KEY UPDATE data = VALUES(data), sort_order = VALUES(sort_order);
INSERT INTO settings (`key`, data) VALUES ('general', '{"siteName":"Punjabi Welfare Trust NGO","topBarText":"PUNJABI WELFARE TRUST NGO","navTitle":"Punjabi Welfare","navSubtitle":"Trust NGO","logo":"/uploads/logo.jpeg","whatsapp":"+917834992799","phone":"+91 78349 92799","email":"punjabiwelfaretrust@gmail.com","instagram":"https://www.instagram.com/punjabiwelfaretrust99?igsh=MXQ0bG52ZzZ1dDl6ZA==","youtube":"https://youtube.com/@punjabiwelfaretrust99"}') ON DUPLICATE KEY UPDATE data = VALUES(data);
INSERT INTO settings (`key`, data) VALUES ('impact', '{"heading":"Our Impact in Action","description":"Watch our volunteers on the ground and see the real-world difference your contributions make."}') ON DUPLICATE KEY UPDATE data = VALUES(data);
INSERT INTO settings (`key`, data) VALUES ('ourWork', '{"heading":"Our Work & Stories","description":"Read about our latest initiatives and the impact we''re making across communities."}') ON DUPLICATE KEY UPDATE data = VALUES(data);
INSERT INTO settings (`key`, data) VALUES ('volunteerSection', '{"tagline":"JOIN OUR FAMILY","heading":"Become a Volunteer","paragraph1":"Join a community of dedicated individuals working towards a better society. Your time is the most valuable gift you can give.","paragraph2":"We believe that lasting change happens when ordinary people come together to do extraordinary things.","quote":"\\"Seva is the essence of life.\\"","quoteSub":"JOIN THE MOVEMENT","image":"/uploads/volunteer.jpeg","formUrl":"https://forms.gle/mJFNbHfyfyvYcEex5"}') ON DUPLICATE KEY UPDATE data = VALUES(data);
INSERT INTO settings (`key`, data) VALUES ('committeeSection', '{"heading":"Our Advisory Committee","description":"We are deeply grateful to the individuals who stand with us. Their generosity fuels our mission to serve humanity."}') ON DUPLICATE KEY UPDATE data = VALUES(data);
INSERT INTO settings (`key`, data) VALUES ('supportersSection', '{"heading":"Our Dedicated Supporters","description":"We are deeply grateful to the individuals who stand with us. Their generosity fuels our mission to serve humanity."}') ON DUPLICATE KEY UPDATE data = VALUES(data);
INSERT INTO settings (`key`, data) VALUES ('volunteersSection', '{"heading":"Our Volunteers","description":"Meet the dedicated young volunteers who are driving change on the ground every day."}') ON DUPLICATE KEY UPDATE data = VALUES(data);
INSERT INTO settings (`key`, data) VALUES ('videosSection', '{"heading":"Watch Us in Action","description":"Watch our volunteers on the ground and see the real-world difference your contributions make.","channelUrl":"https://www.youtube.com/@punjabiwelfaretrust99"}') ON DUPLICATE KEY UPDATE data = VALUES(data);
INSERT INTO settings (`key`, data) VALUES ('feedbackSection', '{"heading":"We Value Your Feedback","description":"Your thoughts and suggestions help us improve our initiatives and reach more people in need."}') ON DUPLICATE KEY UPDATE data = VALUES(data);
INSERT INTO settings (`key`, data) VALUES ('donate', '{"heading":"Ready to Make a Difference?","description":"Your small contribution can save a life, educate a child, or feed a family. Every penny counts and goes directly to the cause.","qrImage":"/uploads/donate-qr.jpeg","qrCaption":"Scan to Donate via UPI","upiId":"79349901@ubin"}') ON DUPLICATE KEY UPDATE data = VALUES(data);
INSERT INTO settings (`key`, data) VALUES ('footer', '{"heading":"Visit Us","description":"Come visit our office and see our work first-hand. We''d love to meet you!","addressLine1":"Sadar Bazar, Delhi Cantt,","addressLine2":"New Delhi, India","hours":"Mon – Sun: 9:00 AM – 6:00 PM","copyright":"© 2025 Punjabi Welfare Trust. All rights reserved."}') ON DUPLICATE KEY UPDATE data = VALUES(data);
INSERT INTO settings (`key`, data) VALUES ('map', '{"heading":"Find Us on the Map","description":"Visit our office in Sadar Bazar, Delhi Cantt. We are always happy to welcome visitors and volunteers.","embedUrl":"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3503.0892547!2d77.1345!3d28.5963!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390d1d6f5c5e5e5f%3A0x1a2b3c4d5e6f7890!2sSadar%20Bazar%2C%20Delhi%20Cantt%2C%20New%20Delhi!5e0!3m2!1sen!2sin!4v1710000000000!5m2!1sen!2sin"}') ON DUPLICATE KEY UPDATE data = VALUES(data);
INSERT INTO settings (`key`, data) VALUES ('certificatesSection', '{"heading":"Honours & Recognition","description":"Punjabi Welfare Trust''s service to society has been recognised by Delhi Police, the Indian Army, BSF and community institutions.","archiveHeading":"Our Certificates & Appreciation Letters","archiveDescription":"Every letter here represents years of ground work — education, relief drives, health camps and community service — recognised by government bodies, armed forces and community institutions."}') ON DUPLICATE KEY UPDATE data = VALUES(data);
